# Generated by Django 5.1.4 on 2025-02-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_billingaddress_line4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='partner',
        ),
    ]
