# Generated by Django 5.1.4 on 2025-02-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_alter_useraddress_options_and_more'),
        ('order', '0020_alter_billingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
