# Generated by Django 5.1.4 on 2025-02-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_remove_line_partner'),
        ('order', '0021_alter_billingaddress_country_and_more'),
    ]

    operations = [
    ]
